# Generated by Django 6.0.2 on 2026-02-09 07:26

import django.db.models.deletion
import nepali_datetime
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2081', max_length=20)),
                ('year_start_date', nepali_datetime_field.models.NepaliDateField(default=nepali_datetime.date.today)),
                ('year_end_date', nepali_datetime_field.models.NepaliDateField(default=nepali_datetime.date.today)),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class / Standard',
                'ordering': ['name', 'section'],
                'unique_together': {('name', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('credit_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('curriculum_version', models.CharField(default='2077/2078', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.standard')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.standard')),
            ],
            options={
                'ordering': ['-academic_year', 'standard'],
                'unique_together': {('teacher', 'standard', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped_out', 'Dropped Out'), ('transferred', 'Transferred'), ('promoted', 'Promoted'), ('failed', 'Failed'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
            options={
                'ordering': ['-academic_year', 'standard'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Assigned ClassTeachers',
                'unique_together': {('subject', 'standard', 'academic_year')},
            },
        ),
    ]
