# Generated by Django 6.0.2 on 2026-02-09 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-academic_year', 'standard']},
        ),
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='classroom',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='teachersubject',
            old_name='classroom',
            new_name='standard',
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('subject', 'standard', 'academic_year')},
        ),
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Standard',
        ),
        migrations.CreateModel(
            name='TeacherStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'ordering': ['-academic_year', 'standard'],
                'unique_together': {('teacher', 'standard', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherClassroom',
        ),
    ]
