# Generated by Django 6.0.2 on 2026-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'academic_year')},
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='roll_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('standard', 'academic_year', 'roll_number'), ('student', 'academic_year')},
        ),
    ]
