# Generated by Django 6.0.2 on 2026-02-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_studentenrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Subject Teachers'},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together={('subject', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='standard',
        ),
    ]
