# Generated by Django 6.0.2 on 2026-02-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teachersubject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Subject Teacher'},
        ),
        migrations.AlterUniqueTogether(
            name='teachersubject',
            unique_together=set(),
        ),
    ]
