# Generated by Django 6.0.2 on 2026-02-25 05:13

import django.db.models.deletion
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_teachersubject_options_and_more'),
        ('accounts', '0006_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g. 101, A1, Lab-1', max_length=20, unique=True)),
                ('room_name', models.CharField(help_text='e.g. Class IX-A, Biology Lab', max_length=100)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('lab', 'Laboratory'), ('library', 'Library'), ('office', 'Office'), ('other', 'Other')], default='classroom', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum students the room can accommodate')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g. Building A, First Floor', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Special features or notes about the room')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room / Classroom',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Dashain, Christmas, Mid-Term Break', max_length=100)),
                ('holiday_type', models.CharField(choices=[('national_holiday', 'National Holiday'), ('school_holiday', 'School Holiday'), ('vacation', 'Vacation / Break'), ('exam_week', 'Exam Week'), ('other', 'Other')], default='school_holiday', max_length=20)),
                ('start_date', nepali_datetime_field.models.NepaliDateField()),
                ('end_date', nepali_datetime_field.models.NepaliDateField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holiday Calendar',
                'ordering': ['academic_year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(help_text='e.g., 1, 2, 3...')),
                ('period_name', models.CharField(blank=True, help_text='e.g., Period 1, Assembly, Recess', max_length=50)),
                ('start_time', models.TimeField(help_text='e.g., 09:00')),
                ('end_time', models.TimeField(help_text='e.g., 09:45')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_break', models.BooleanField(default=False, help_text='Mark if this is a break/recess period')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Time Slot / Period',
                'ordering': ['academic_year', 'period_number'],
                'unique_together': {('academic_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('is_available', models.BooleanField(default=True, help_text='True if teacher is available, False if busy/leave')),
                ('reason', models.CharField(blank=True, help_text='e.g., Staff Meeting, Training, Leave', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_availability', to='academics.academicyear')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.timeslot')),
            ],
            options={
                'verbose_name': 'Teacher Availability',
                'verbose_name_plural': 'Teacher Availability',
                'ordering': ['teacher', 'day', 'time_slot'],
                'unique_together': {('academic_year', 'teacher', 'day', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('is_optional', models.BooleanField(default=False, help_text='Mark if attendance is optional')),
                ('remarks', models.TextField(blank=True, help_text='e.g., Project work, Guest lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_timetables', to='academics.academicyear')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.standard')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.timeslot')),
            ],
            options={
                'verbose_name': 'Class Timetable',
                'verbose_name_plural': 'Class Timetables',
                'ordering': ['standard', 'day', 'time_slot'],
                'unique_together': {('academic_year', 'standard', 'day', 'time_slot')},
            },
        ),
    ]
