# Generated by Django 6.0.2 on 2026-02-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('result_published', 'Result Published'), ('attendance_marked', 'Attendance Marked'), ('exam_scheduled', 'Exam Scheduled'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('grade_updated', 'Grade Updated'), ('document_uploaded', 'Document Uploaded'), ('announcement', 'Announcement'), ('system_alert', 'System Alert')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('result_published', models.BooleanField(default=True, help_text='Notify when exam results are published')),
                ('attendance_marked', models.BooleanField(default=True, help_text='Notify when attendance is recorded')),
                ('exam_scheduled', models.BooleanField(default=True, help_text='Notify when exams are scheduled')),
                ('enrollment_confirmed', models.BooleanField(default=True, help_text='Notify on enrollment confirmation')),
                ('grade_updated', models.BooleanField(default=True, help_text='Notify when grades are updated')),
                ('document_uploaded', models.BooleanField(default=False, help_text='Notify when documents are uploaded')),
                ('announcement', models.BooleanField(default=True, help_text='Notify of school announcements')),
                ('system_alert', models.BooleanField(default=True, help_text='Notify of important system alerts')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start time (HH:MM)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end time (HH:MM)', null=True)),
                ('digest_enabled', models.BooleanField(default=False, help_text='Receive daily digest instead of instant notifications')),
                ('digest_time', models.TimeField(default='09:00', help_text='Time to send daily digest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
