# Generated by Django 6.0.2 on 2026-02-09 07:26

import django.db.models.deletion
import nepali_datetime
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. First Terminal Examination 2081', max_length=100)),
                ('term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('final_term', 'Final Term'), ('unit_test', 'Unit Test')], max_length=20)),
                ('start_date', nepali_datetime_field.models.NepaliDateField()),
                ('end_date', nepali_datetime_field.models.NepaliDateField()),
                ('is_published', models.BooleanField(default=False, help_text='Set to true to show results to students/parents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', nepali_datetime_field.models.NepaliDateField()),
                ('full_marks_theory', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('pass_marks_theory', models.DecimalField(decimal_places=2, default=27.0, max_digits=5)),
                ('full_marks_practical', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('pass_marks_practical', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='activities.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', nepali_datetime_field.models.NepaliDateField(default=nepali_datetime.date.today)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'On Leave')], default='present', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.standard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('date', 'student', 'subject', 'standard')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained_theory', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marks_obtained_practical', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subject_grade_point', models.DecimalField(decimal_places=2, editable=False, max_digits=3)),
                ('subject_grade', models.CharField(editable=False, max_length=5)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'exam_subject')},
            },
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Result Summaries',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
