# Generated by Django 6.0.2 on 2026-02-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_studentenrollment_options_and_more'),
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='classroom',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='examsubject',
            old_name='classroom',
            new_name='standard',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'student', 'subject', 'standard')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject', 'standard')},
        ),
    ]
