# Generated by Django 6.0.2 on 2026-02-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teachersubject_options_and_more'),
        ('activities', '0005_alter_result_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject'),
        ),
    ]
