# Generated by Django 6.0.2 on 2026-02-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_studentenrollment_unique_together_and_more'),
        ('activities', '0006_alter_examsubject_subject'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('activities', 'ResultSummary').objects.all().delete(),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='resultsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.studentenrollment'),
        ),
    ]
