# Generated by Django 6.0.2 on 2026-02-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_examsubject_options_alter_result_options'),
        ('activities', '0008_resultsummary_results'),
    ]

    operations = [
    ]
