# Generated by Django 6.0.2 on 2026-02-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_merge_20260210_1121'),
        ('activities', '0009_resultsummary_results_through'),
    ]

    operations = [
    ]
