# Generated by Django 6.0.2 on 2026-02-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_teachersubject_options_and_more'),
        ('activities', '0012_remove_studentresultsummary_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarksheet',
            fields=[
            ],
            options={
                'verbose_name': 'Student Marksheet',
                'verbose_name_plural': 'Student Marksheets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.studentenrollment',),
        ),
    ]
