# Generated by Django 6.0.2 on 2026-02-13 02:37

import datetime
import nepali_datetime
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, help_text='Date of birth in AD'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth_bs',
            field=nepali_datetime_field.models.NepaliDateField(default=nepali_datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, help_text='Date of birth in AD'),
        ),
    ]
